In [1]:
import torch
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
print(torch.__version__)

1.12.1


# Tensors

### Scalar Tensor

In [15]:
scalar = torch.tensor(7)
scalar.item()

7

### Vector Tensor

In [16]:
vector = torch.tensor([7,7])

In [17]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

### Matrix Tensor

In [20]:
MATRIX = torch.tensor([[7,7], [8,8], [9,9]])

# Random Tensor

In [35]:
RAND_TENSOR = torch.rand(size=(3,3))

In [36]:
RAND_TENSOR

tensor([[0.1637, 0.6263, 0.7663],
        [0.7346, 0.3872, 0.8702],
        [0.8850, 0.5652, 0.5354]])

# Zeros and Ones Tensor

In [37]:
zero_tensor = torch.zeros(size=(5,4))

In [38]:
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
one_tensor = torch.ones(size=(5,4))

In [40]:
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Creating range of Tensors

In [58]:
range_till_hundred_by_two = torch.arange(0,100).reshape(2,5,10)

In [59]:
range_till_hundred_by_two

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [60]:
zero_like = torch.zeros_like(range_till_hundred_by_two)

In [62]:
zero_like

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [81]:
float_16_tensor = torch.tensor([x for x in range(100000005)],
                               dtype=torch.float64, # it determines datatype of elements
                               device='cuda', # it 
                               requires_grad=False
                              )

In [85]:
float_16_tensor2 = torch.tensor([x for x in range(100000005)],
                               dtype=torch.float64, # it determines datatype of elements
                               device='cuda', # it 
                               requires_grad=False
                              )

In [88]:
type(float_16_tensor2.type(torch.float32))

torch.Tensor